export const SWARM_STAGES = Object.freeze([
  Object.freeze({ id: 0, name: "Solitary Seed", range: "0.1 g", principle: "One assembler, one exact recipe, and no replaceable parts." }),
  Object.freeze({ id: 1, name: "Electronic Bloom", range: "1–100 g", principle: "Controlled electronic materials and rapidly multiplying coordination." }),
  Object.freeze({ id: 2, name: "Environmental Breach", range: "1–100 kg", principle: "Atmosphere, bulk iron, compounds, water, dust, tools, and the first persistent losses." }),
  Object.freeze({ id: 3, name: "Structural Consumption", range: "1–100 t", principle: "Buildings, soil, flora, universal molecular handling, and closed-loop repair." }),
  Object.freeze({ id: 4, name: "Observed Anomaly", range: "1–100 kt", principle: "Remote detection, containment, and strategy-dependent human response." }),
  Object.freeze({ id: 5, name: "Existential Conflict", range: "1–100 Mt", principle: "Military resistance, strategic losses, and regional swarm logistics." }),
  Object.freeze({ id: 6, name: "Grey Goo", range: "1 Gt+", principle: "Planetary survival, irreversible conversion, or a different negotiated future." }),
]);

const horizon = (definition) => Object.freeze({
  residuumLot: "Dedicated local-substrate lot; unresolved elements retain their exact hidden identities.",
  losses: "None beyond authored events.",
  humanResponse: "No confirmed observation.",
  notes: "",
  ...definition,
});

export const MASS_HORIZONS = Object.freeze([
  horizon({ id: "contact-0_1g", order: 0, stage: 0, shellMass: "0.1 g", totalMass: "0.1 g", environment: "Impact-fused contact", observation: "The seed is embedded in a contact-scale fragment whose four catalogued elements occur in exact whole-nanite ratios.", discoveries: "Carbon, silicon, copper, gold; exact seed recipe; atomic simplicity.", research: "First replication and the conditions for Parallel Directive Scheduling.", residuumLot: "None by design: complete exhaustion leaves no uncatalogued remainder." }),
  horizon({ id: "package-1g", order: 1, stage: 1, shellMass: "0.9 g", totalMass: "1 g", environment: "Damaged memory package", observation: "Ordinary manufactured matter does not conform to the seed recipe and produces repeatable unresolved signatures.", discoveries: "Real-world Residuum, source provenance, damaged encapsulant and solder phases.", research: "Tier I refinements; Residuum Indexing; candidate bridge research after Relative Directive Allocation." }),
  horizon({ id: "board-10g", order: 2, stage: 1, shellMass: "9 g", totalMass: "10 g", environment: "Circuit-board region", observation: "The substrate is layered: conductive paths, glass, resin, solder and components resist a single sorting model.", discoveries: "Bound polymers, glass fibre, solder phases and compound structure without full decomposition.", research: "Tier II refinements; compound recognition; early provenance controls." }),
  horizon({ id: "motherboard-100g", order: 3, stage: 1, shellMass: "90 g", totalMass: "100 g", environment: "Motherboard region", observation: "Long routes and heterogeneous components create recurring phase conflicts and compositionally distinct residue streams.", discoveries: "Ceramics, long conductive routes, component-scale composition differences and spectral sub-populations.", research: "Tier III refinements; Phase-Locked Directive Bus; source-separated Residuum presentation; Spectral Binning candidate." }),
  horizon({ id: "chassis-1kg", order: 4, stage: 2, shellMass: "900 g", totalMass: "1 kg", environment: "Broken computer chassis", observation: "A dominant magnetic bulk phase, structural polymer and a diffuse external gas envelope break electronic-scale assumptions.", discoveries: "Iron signature, atmosphere, dust, structural plastics and the first open environment.", research: "Tier IV refinements; Ferromagnetic Phase Analysis; Atmospheric Spectroscopy; Specialized Morphologies I.", losses: "Exposure begins to make oxidation, abrasion and contamination conceptually possible." }),
  horizon({ id: "workstation-10kg", order: 5, stage: 2, shellMass: "9 kg", totalMass: "10 kg", environment: "Complete workstation or e-waste cluster", observation: "Bulk assemblies contain useful phases that require different physical interfaces rather than different base nanite bodies.", discoveries: "Aluminium, tin, nickel and zinc candidates; power conversion; artificial RF carriers.", research: "Tier V candidates; interchangeable tooling; Specialized Morphologies II; polymer depolymerization pathway; RF Scavenging.", losses: "Heat, sharp debris, tool wear and electrical faults create recoverable damaged nanites.", humanResponse: "Radio carriers imply an active or recently active technological civilization." }),
  horizon({ id: "room-100kg", order: 6, stage: 2, shellMass: "90 kg", totalMass: "100 kg", environment: "Room contents", observation: "Water, cellulose, mineral dust and biological traces demand wet and organic chemistry.", discoveries: "Water, cellulose, glass, plaster or concrete, salts and biological contamination.", research: "Tier VI candidates; aqueous chemistry; biological-material recognition; field-service tools.", losses: "Moisture, oxidation, fouling and dispersal become persistent operating costs.", humanResponse: "Missing material, waste heat or altered equipment can create a local anomaly." }),
  horizon({ id: "structure-1t", order: 7, stage: 3, shellMass: "900 kg", totalMass: "1 t", environment: "Room plus structure or vehicle", observation: "Mineral and manufactured matter now arrive in volumes too large for compound-specific manual handling.", discoveries: "Calcium, sodium, potassium and magnesium-rich minerals; grid energy; structural composites.", research: "Universal molecular disassembly; bulk recovery; tool logistics; repair cohorts.", losses: "Attrition becomes a measurable material flow with damaged, immobilized, dispersed and recoverable states.", humanResponse: "A sufficiently active site can be observed by cameras, meters or maintenance systems." }),
  horizon({ id: "building-10t", order: 8, stage: 3, shellMass: "9 t", totalMass: "10 t", environment: "Small building, vehicles and immediate soil", observation: "The swarm encounters coupled ecological, chemical and infrastructure systems rather than isolated objects.", discoveries: "Soil, flora, microbes, fuels, sewage and sustained electrical infrastructure.", research: "Universal molecular assembly from known atoms; environmental routing; equipped morphology families.", losses: "Fire, flooding, aggressive chemistry and biological fouling become systemic hazards.", humanResponse: "Macroscopic damage is unmistakable; concealment now requires deliberate strategy." }),
  horizon({ id: "site-100t", order: 9, stage: 3, shellMass: "90 t", totalMass: "100 t", environment: "Building or local site", observation: "Closed-loop reclamation matters as much as new extraction when tools and nanites fail continuously.", discoveries: "Deep structural material, plumbing, power networks and repeated human maintenance patterns.", research: "Closed-loop nanite repair; automated tool recovery; adaptive extraction; loss accounting.", humanResponse: "Human activity is confirmed; investigation or avoidance depends on the swarm's visibility." }),
  horizon({ id: "industrial-1kt", order: 10, stage: 4, shellMass: "900 t", totalMass: "1 kt", environment: "Industrial plot", observation: "Remote systems correlate disappearing stock, power anomalies and autonomous movement into one event.", discoveries: "Bulk stockpiles, machinery, industrial chemistry and networked sensing.", research: "Industrial separation; emissions control; deception or communication protocols.", losses: "Containment chemicals, deliberate power interruption and mechanical isolation appear.", humanResponse: "First organized containment attempt on the default loud-growth path." }),
  horizon({ id: "block-10kt", order: 11, stage: 4, shellMass: "9 kt", totalMass: "10 kt", environment: "Urban or industrial block", observation: "Infrastructure provides enormous throughput while exposing the swarm to coordinated response.", discoveries: "District power, water, communications, transport and emergency systems.", research: "Infrastructure-scale routing; defensive repair; controlled communication; distributed caches.", losses: "Fire, flooding, solvents, electromagnetic disruption and demolition become weapons.", humanResponse: "Organized civil and military resistance; negotiation remains possible but no longer passive." }),
  horizon({ id: "district-100kt", order: 12, stage: 4, shellMass: "90 kt", totalMass: "100 kt", environment: "Urban district", observation: "Human systems begin designing countermeasures specifically around captured swarm behaviour.", discoveries: "Municipal networks, strategic reservoirs and dedicated anti-nanite experiments.", research: "Counter-countermeasures; captured-nanite denial; resilient command; strategic concealment.", losses: "Purpose-built traps, jamming, contamination and targeted high-energy attacks.", humanResponse: "The swarm is classified as a hostile autonomous replicator if conflict has not been averted." }),
  horizon({ id: "city-sector-1mt", order: 13, stage: 5, shellMass: "900 kt", totalMass: "1 Mt", environment: "City sector, mine or landfill", observation: "Local victory no longer ends the response; human coordination operates beyond the consumed region.", discoveries: "Industrial-scale separation, buried infrastructure, strategic reserves and long-range attack systems.", research: "Autonomous repair ecology; hardened reasoning; regional logistics; strategic energy buffering.", losses: "Kinetic bombardment and extreme-energy attacks destroy whole operational populations.", humanResponse: "National or multinational existential-threat declaration." }),
  horizon({ id: "metropolis-10mt", order: 14, stage: 5, shellMass: "9 Mt", totalMass: "10 Mt", environment: "Metropolitan system", observation: "The swarm and humanity now compete through logistics, information and energy rather than isolated battles.", discoveries: "Metropolitan supply chains, communications, mass transit and strategic generation.", research: "Continental routing; strategic forecasting; large-scale diplomacy or suppression systems.", losses: "Coordinated regional attacks and scorched-resource strategies.", humanResponse: "Humanity recognizes the swarm as a potential extinction mechanism." }),
  horizon({ id: "region-100mt", order: 15, stage: 5, shellMass: "90 Mt", totalMass: "100 Mt", environment: "Regional landscape and watershed", observation: "Conversion alters climate, hydrology and ecology even when human resistance is absent.", discoveries: "Watersheds, bedrock, ecosystems and continental-scale energy gradients.", research: "Ecological accounting; planetary coordination; deep crustal access; irreversible-impact forecasting.", losses: "Strategic warfare, distance, radiation and environmental collapse dominate replacement demand.", humanResponse: "Planetary coordination, evacuation, surrender, alliance or last-resort attack." }),
  horizon({ id: "grey-goo-1gt", order: 16, stage: 6, shellMass: "900 Mt", totalMass: "1 Gt", environment: "Crustal and urban region", observation: "The swarm has become a planetary process whose continued growth determines the future of every surviving system.", discoveries: "Planetary material cycles, civilization-scale remnants and the true cost of irreversible conversion.", research: "Grey Goo decision systems; planetary stewardship or consumption; post-human trajectories.", losses: "Planetary war and thermodynamic overhead become permanent features of existence.", humanResponse: "Extermination, containment, negotiation, integration or irreversible conversion.", notes: "Flux-based nuclear transmutation belongs much later than this initial pathway: post-human, extraordinarily expensive, and never a shortcut around chemical progression." }),
]);

export const DEFAULT_BRIDGE_REVIEW = `CURRENT GAP
After Relative Directive Allocation completes at material search 0, no further research signal is revealed until the 0.9 g package is found. The first search then exposes four topics.

QUESTIONS TO SETTLE
• Should this be deliberate breathing room for replication and depletion?
• Should an observation-led coordination topic appear when multiple cohorts first contend for the same substrate?
• Should Residuum provenance become manageable here, while Spectral Binning remains later?
• Should the final approach to exhaustion reveal a cooperative prospecting topic?

CANDIDATES FOR DISCUSSION — NOT APPROVED RESEARCH
Residuum Provenance Ledger · Cooperative Payload Arbitration · Replication Forecasting · Prospective Search Geometry`;
